grpc-server:
  port: 9090
  test: false
http-server:
  port: 8080
  test: true
kafka:
  verbose: true
  client-name: backend-example
  brokers:
    - localhost:9094
  consumers:
    - name: test-consumer-name
      consumer-group: test-consumer
      topics:
        - test-consumer-topic
      config:
  producers:
    - name: test-producer-name
      topic: test-producer-topic
      config:

