grpc-server:
  port: 9090
  test: false
http-server:
  port: 8080
  test: true
kafka:
  client-name: backend-example
  brokers:
    - localhost:9092
  consumers:
    - name: test-consumer-name
      topics:
        - name: test-consumer-topic-name
          topics:
            - test-consumer-topic
      config:
  producers:
    - name: test-producer-name
      topics:
        - name: test-producer-topic-name
          topics:
            - test-producer-topic
      config:

