app:
  production: false
grpc-server:
  port: 9090
http-server:
  port: 8080
kafka:
  verbose: false
  client-name: backend-example
  brokers:
    - localhost:9094
  consumers:
    - name: test-consumer-name
      consumer-group: test-consumer
      topics:
        - test-consumer-topic
      config:
  producers:
    - name: test-producer-name
      topic: test-producer-topic
      config:

